# Generated by Django 6.0.3 on 2026-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_warehouse'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_lookup',
            field=models.CharField(blank=True, help_text='SHA-256 lookup hash for fast PIN search', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('pin_lookup__gt', '')), fields=('warehouse', 'pin_lookup'), name='user_warehouse_pin_lookup_uniq'),
        ),
    ]
