# Generated by Django 6.0.3 on 2026-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pin_lookup_field'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Additional warehouses this user can work at', related_name='accessible_users', to='warehouse.warehouse'),
        ),
    ]
