# Generated by Django 5.2.8 on 2026-03-21 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from shared.db import schema_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('picking', 'Picking'), ('packed', 'Packed'), ('done', 'Done')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1 = highest, 9 = lowest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('customer', models.CharField(blank=True, max_length=256)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehouse.warehouse')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.wave')),
            ],
            options={
                'db_table': schema_table('warehouse', 'orders_order'),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_req', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qty_picked', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('location', models.ForeignKey(blank=True, help_text='Assigned pick location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'db_table': schema_table('warehouse', 'orders_orderline'),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'priority'], name='warehouse_o_status_e0b1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['warehouse', 'status'], name='warehouse_o_warehou_6d93fc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'item'], name='warehouse_o_order_i_67e882_idx'),
        ),
    ]
