# Generated by Django 5.2.8 on 2026-03-21 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from shared.db import schema_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('channel_type', models.CharField(choices=[('rest', 'REST'), ('csv', 'CSV'), ('xml', 'XML'), ('sftp', 'SFTP')], max_length=20)),
                ('direction', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=256)),
                ('schedule', models.CharField(blank=True, max_length=64)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='warehouse.warehouse')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_integrationconfig'),
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('done', 'Done')], default='planned', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='warehouse.warehouse')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_wave'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('picking', 'Picking'), ('putaway', 'Putaway'), ('move', 'Move'), ('shipping', 'Shipping')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('priority', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tasks', to='warehouse.location')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_tasks', to='warehouse.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='warehouse.warehouse')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.wave')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_task'),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='nearest_neighbor', max_length=64)),
                ('points', models.JSONField(default=list)),
                ('distance_m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eta_seconds', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='operations.task')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='operations.wave')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_route'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations.integrationconfig')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_integrationlog'),
                'indexes': [models.Index(fields=['config', 'created_at'], name='operations__config__17bfb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('throughput_lines', models.PositiveIntegerField(default=0)),
                ('throughput_orders', models.PositiveIntegerField(default=0)),
                ('order_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dock_to_stock_p95', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sla_on_time', models.PositiveIntegerField(default=0)),
                ('sla_overdue', models.PositiveIntegerField(default=0)),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('idle_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='warehouse.warehouse')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_kpisnapshot'),
                'indexes': [models.Index(fields=['warehouse', 'period_start'], name='operations__warehou_9a435a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.warehouse')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='operations.task')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_event'),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='operations__event_t_dfa2d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('expected_barcode', models.CharField(blank=True, max_length=64)),
                ('expected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('actual_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_steps', to='warehouse.location')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='operations.task')),
            ],
            options={
                'db_table': schema_table('operations', 'operations_taskstep'),
                'constraints': [models.UniqueConstraint(fields=('task', 'sequence'), name='operations_taskstep_task_sequence_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='wave',
            index=models.Index(fields=['warehouse', 'status'], name='operations__warehou_490e18_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='operations__status_db28a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['warehouse', 'status'], name='operations__warehou_1fd3de_idx'),
        ),
    ]
