# Generated by Django 5.2.8 on 2026-03-21 10:40

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models

from shared.db import schema_table


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('barcode', models.CharField(blank=True, max_length=64, unique=True)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('dimensions', models.JSONField(default=dict, help_text='{"l": 10, "w": 5, "h": 3}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': schema_table('warehouse', 'inventory_item'),
                'indexes': [models.Index(fields=['sku'], name='warehouse_i_sku_b922ba_idx'), models.Index(fields=['barcode'], name='warehouse_i_barcode_c500a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('available_qty', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('reserved_qty')), output_field=models.DecimalField(decimal_places=3, max_digits=12))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='warehouse.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='inventory.item')),
            ],
            options={
                'db_table': schema_table('warehouse', 'inventory_inventory'),
                'indexes': [models.Index(fields=['item', 'available_qty'], name='warehouse_i_item_id_d3102e_idx'), models.Index(fields=['location'], name='warehouse_i_locatio_1827e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'location'), name='inventory_item_location_uniq')],
            },
        ),
    ]
